server:
  port: 8090

spring:
  application:
    name: interview

  jpa:
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
    show-sql: false
    properties:
      hibernate:
        generate_statistics: true
    open-in-view: false

  datasource:
#    url: jdbc:h2:mem:interview
    url: jdbc:h2:tcp://localhost:9092/~/.demo/interview
    username: sa
    password: sa

logging:
  level:
    org:
      springframework.web:
        filter: debug
#        servlet.DispatcherServlet: debug
      hibernate:
        engine: warn #info to show session times
        type: info #trace to show binding parameters
        SQL: debug #debug to show generated sql
        stat: debug #debug to show hql query times
